version: '3'

services:
  web:
    build: .
    
    container_name: web-app
    
    ports:
      - 5000:5000
    
    depends_on:
      - db
  
  db:
    image: mongo
    
    restart: always

    ports:
      - 27017:27017
    
    environment:
      - MONGO_INITDB_DATABASE=api_auth
    
    volumes:
      - ./mongodb_data:/data/db
